207 organisation replacement
CirclesUBI/circles-core pull request #227
Opened 2023-08-31 15:05 UTC by JacqueGM

2023-09-04 10:35 UTC, juanenrisley requested changes
The jsdocs should be review before merging. All comments for the organization module methods must be updated.

2023-09-04 15:03 UTC, JacqueGM commented on src/organization.js
> +        data: hub.methods.trust(options.from, 100).encodeABI(),
done

2023-09-05 07:46 UTC, juanenrisley approved these changes
👍🏿 Alrighty!

2023-09-27 13:26 UTC, juanenrisley approved these changes
👍🏿 <3

2023-09-27 14:26 UTC, juanenrisley approved these changes
👍🏿

2023-09-28 08:57 UTC, merged